"""Closed catalog of audit action codes (RN-24).

Every action code used in AuditService.log() must appear in VALID_ACTION_CODES.
Adding a new code requires updating this file — making the catalog explicitly versioned.
"""

# Active in C-05
IMPERSONACION_INICIAR = "IMPERSONACION_INICIAR"
IMPERSONACION_FINALIZAR = "IMPERSONACION_FINALIZAR"

# C-07+
CALIFICACIONES_IMPORTAR = "CALIFICACIONES_IMPORTAR"
PADRON_CARGAR = "PADRON_CARGAR"
ASIGNACION_MODIFICAR = "ASIGNACION_MODIFICAR"
LIQUIDACION_CERRAR = "LIQUIDACION_CERRAR"

# C-12 — comunicaciones (RN-23, Q2 de la propuesta)
COMUNICACION_ENVIAR = "COMUNICACION_ENVIAR"
COMUNICACION_APROBAR = "COMUNICACION_APROBAR"

# C-14 — evaluaciones-y-coloquios
RESULTADO_REGISTRAR = "RESULTADO_REGISTRAR"

VALID_ACTION_CODES: frozenset[str] = frozenset(
    {
        IMPERSONACION_INICIAR,
        IMPERSONACION_FINALIZAR,
        CALIFICACIONES_IMPORTAR,
        PADRON_CARGAR,
        COMUNICACION_ENVIAR,
        COMUNICACION_APROBAR,
        ASIGNACION_MODIFICAR,
        LIQUIDACION_CERRAR,
        RESULTADO_REGISTRAR,
    }
)
